import {Header} from "@repo/ui/src/components/header";

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body>
        <header className="border-b">
            <div className="container mx-auto px-4 py-4">
                <Header/>
            </div>
        </header>
        {children}
        </body>
        </html>
    )
}
